[config]
schemaVersion = "0.0.1"


[package]
namespace = "CrazyPenguin"
name = "Argus"
versionNumber = "0.0.6"
description = "Argus is a Hades II mod that supports the Argus Twitch extension. It will show your viewers various details about your run. Make sure to check out the README below for installation instructions!"
websiteUrl = "https://github.com/bmilojkovic/argus-h2-mod"
containsNsfwContent = false

[package.dependencies]
Hell2Modding-Hell2Modding = "1.0.70"
LuaENVY-ENVY = "1.2.0"
SGG_Modding-Chalk = "2.1.1"
SGG_Modding-ReLoad = "1.0.2"
SGG_Modding-SJSON = "1.0.0"
SGG_Modding-ModUtil = "4.0.1"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"


[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "mods", ]
